default:
  image: python:3.11-slim
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install build twine

stages:
  - build
  - test
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

build:
  stage: build
  variables:
    GIT_DEPTH: 0
  script:
    - apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*
    - python -m build
  artifacts:
    paths:
      - dist/

glpk:
  stage: test
  variables:
    SOLVER: glpk
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc g++ glpk-utils libglpk-dev && rm -rf /var/lib/apt/lists/*
    - pip install -r requirements.txt
    - pip install dist/*.whl
    - export PYTHONPATH=src
    - pytest --cov-report term-missing --cov=src tests/

gurobi:
  image: gurobi/python
  stage: test
  variables:
    SOLVER: gurobi
  script:
    - apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - export GRB_LICENSE_FILE=.secure_files/gurobi.lic
    - pip install -r requirements.txt
    - pip install dist/*.whl
    - export PYTHONPATH=src
    - pytest --cov-report term-missing --cov=src tests/


publish:
  stage: publish
  only:
    - tags
    - master
  script:
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*